name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: |
        echo ${{ secrets.DOCKER_USER }} | docker login -u ${{ secrets.DOCKER_PASSWORD }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file dev/docker/Dockerfile --tag bolkedebruin/rdpgw:$(date +%s)
    - name: Publish
      run: docker push bolkedebruin/rdpgw
